USE Users;

CREATE TABLE Notifications(
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(15) NOT NULL,
user_id INT NOT NULL,
noti_username VARCHAR(15) NOT NULL,
noti_user_id INT NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
is_read BOOLEAN DEFAULT FALSE, 
noti_type VARCHAR(15) NOT NULL,
post_id INT NULL,
FOREIGN KEY (username) REFERENCES Users(username) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
FOREIGN KEY (noti_username) REFERENCES Users(username) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (noti_user_id) REFERENCES Users(id) ON DELETE CASCADE, 
FOREIGN KEY (post_id) REFERENCES Tweets(id) ON DELETE CASCADE
);

SELECT * FROM Notifications;